/// CassetteDSPTests.swift — Golden-vector XCTests for CassetteDSP.
///
/// Tests load WAV fixtures generated by make_fixtures.py and assert Swift
/// results agree with the Python reference within the stated tolerances.
///
/// Fixture layout (relative to Tests/fixtures/):
///   chirp_fixture.wav   — global up-chirp at known offset in noise.
///   sounder_fixture.wav — Schroeder multitone + silence sections.
///   clip_fixture.wav    — clipped 1 kHz sine.
///   expected.json       — ground-truth values + tolerances.

import XCTest
import AVFoundation
@testable import CassetteDSP

// MARK: - Fixture loader helpers

private struct ChirpExpected: Decodable {
    let chirp_offset_samples:  Int
    let chirp_n_samples:       Int
    let total_samples:         Int
    let sample_rate:           Int
    let tolerance_samples:     Int
}

private struct SounderExpected: Decodable {
    let mt_start_sample:           Int
    let mt_length_samples:         Int
    let sil_start_sample:          Int
    let sil_length_samples:        Int
    let expected_snr_db_median:    Double
    let expected_snr_db_p10:       Double
    let expected_frac_below_8db:   Double
    let expected_noise_floor_dbfs: Double
    let tolerance_snr_db:          Double
    let tolerance_nf_db:           Double
}

private struct ClipExpected: Decodable {
    let expected_clip_fraction:    Double
    let clipping_threshold:        Double
    let tolerance_relative:        Double
}

private struct AllExpected: Decodable {
    let chirp:   ChirpExpected
    let sounder: SounderExpected
    let clip:    ClipExpected
}

/// Resolve the fixtures/ directory relative to this source file.
/// This works when running `swift test` on macOS because #filePath is a
/// compile-time constant with the absolute path of this source file.
private func fixturesDir() -> URL {
    let thisFile = URL(fileURLWithPath: #filePath)
    // Tests/CassetteDSPTests/CassetteDSPTests.swift -> Tests/ -> fixtures/
    return thisFile
        .deletingLastPathComponent()   // CassetteDSPTests/
        .deletingLastPathComponent()   // Tests/
        .appendingPathComponent("fixtures")
}

private func fixtureURL(_ name: String) -> URL {
    fixturesDir().appendingPathComponent(name)
}

private func loadExpected() throws -> AllExpected {
    let data = try Data(contentsOf: fixtureURL("expected.json"))
    return try JSONDecoder().decode(AllExpected.self, from: data)
}

/// Read a WAV or CAF file into a mono [Float] array using AVFoundation.
private func readWAV(_ name: String) throws -> (samples: [Float], sr: Int) {
    let url = fixtureURL(name)
    let file = try AVAudioFile(forReading: url)
    let sr = Int(file.fileFormat.sampleRate)
    let frameCount = AVAudioFrameCount(file.length)

    // If file is stereo, create a stereo read buffer then mix.
    let fileFmt = AVAudioFormat(commonFormat: .pcmFormatFloat32,
                                sampleRate: file.fileFormat.sampleRate,
                                channels: file.fileFormat.channelCount,
                                interleaved: false)!
    let buf = AVAudioPCMBuffer(pcmFormat: fileFmt, frameCapacity: frameCount)!
    try file.read(into: buf)
    let count = Int(buf.frameLength)
    let nCh = Int(buf.format.channelCount)

    var mono = [Float](repeating: 0, count: count)
    if nCh == 1 {
        let ptr = buf.floatChannelData![0]
        mono = Array(UnsafeBufferPointer(start: ptr, count: count))
    } else {
        for ch in 0..<nCh {
            let ptr = buf.floatChannelData![ch]
            for i in 0..<count { mono[i] += ptr[i] }
        }
        let scale = Float(1.0 / Double(nCh))
        for i in 0..<count { mono[i] *= scale }
    }
    return (mono, sr)
}

// MARK: - Chirp sync tests

final class ChirpSyncTests: XCTestCase {
    func testChirpDetection() throws {
        let exp = try loadExpected()
        let (samples, _) = try readWAV("chirp_fixture.wav")

        let detector = ChirpSync()
        let result = detector.detect(samples, isUpChirp: true)

        let expectedOffset = exp.chirp.chirp_offset_samples
        let tol = exp.chirp.tolerance_samples

        XCTAssertGreaterThan(result.normalizedCorrelation, 0.2,
                             "Correlation too low — chirp not detected. Got \(result.normalizedCorrelation)")
        XCTAssertEqual(result.sampleOffset, expectedOffset, accuracy: tol,
                       "Chirp offset \(result.sampleOffset) not within ±\(tol) of \(expectedOffset)")
    }

    func testDownChirpDetectionDoesNotCrash() throws {
        let (samples, _) = try readWAV("chirp_fixture.wav")
        let detector = ChirpSync()
        let result = detector.detect(samples, isUpChirp: false)
        XCTAssertGreaterThanOrEqual(result.sampleOffset, 0)
        XCTAssertLessThan(result.sampleOffset, samples.count)
    }
}

// MARK: - Sounder analyzer tests

final class SounderAnalyzerTests: XCTestCase {
    func testSNRMedianAndNoiseFloor() throws {
        let exp = try loadExpected()
        let (samples, _) = try readWAV("sounder_fixture.wav")

        let se = exp.sounder
        let trim = Int(0.3 * 48_000.0)   // 0.3 s trim — matches Python

        // Extract multitone segment (trimmed each end).
        let mtStart  = se.mt_start_sample + trim
        let mtEnd    = se.mt_start_sample + se.mt_length_samples - trim
        let mtTrimmed = Array(samples[mtStart ..< mtEnd])

        // Extract silence segment (trimmed each end).
        let silStart = se.sil_start_sample + trim
        let silEnd   = se.sil_start_sample + se.sil_length_samples - trim
        let silTrimmed = Array(samples[silStart ..< silEnd])

        let analyzer = SounderAnalyzer()
        let metrics  = analyzer.analyze(
            multitoneSegment: mtTrimmed,
            silenceSegment:   silTrimmed)

        XCTAssertEqual(metrics.snrDBMedian,
                       se.expected_snr_db_median,
                       accuracy: se.tolerance_snr_db,
                       "SNR median \(metrics.snrDBMedian) not within ±\(se.tolerance_snr_db) dB of \(se.expected_snr_db_median)")

        XCTAssertEqual(metrics.snrDBP10,
                       se.expected_snr_db_p10,
                       accuracy: se.tolerance_snr_db,
                       "SNR p10 \(metrics.snrDBP10) not within ±\(se.tolerance_snr_db) dB of \(se.expected_snr_db_p10)")

        if let nf = metrics.noiseFloorDBFS {
            XCTAssertEqual(nf,
                           se.expected_noise_floor_dbfs,
                           accuracy: se.tolerance_nf_db,
                           "Noise floor \(nf) not within ±\(se.tolerance_nf_db) dB of \(se.expected_noise_floor_dbfs)")
        } else {
            XCTFail("noiseFloorDBFS is nil — silence segment not processed")
        }
    }

    func testFracBelow8dB() throws {
        let exp = try loadExpected()
        let (samples, _) = try readWAV("sounder_fixture.wav")

        let se = exp.sounder
        let trim = Int(0.3 * 48_000.0)

        let mtStart  = se.mt_start_sample + trim
        let mtEnd    = se.mt_start_sample + se.mt_length_samples - trim
        let mtTrimmed = Array(samples[mtStart ..< mtEnd])

        let analyzer = SounderAnalyzer()
        let metrics  = analyzer.analyze(multitoneSegment: mtTrimmed)

        // For clean fixture, frac_below_8db should equal expected (±0.05 absolute).
        XCTAssertLessThanOrEqual(
            metrics.fracBelow8dB,
            se.expected_frac_below_8db + 0.05,
            "fracBelow8dB \(metrics.fracBelow8dB) exceeds expected \(se.expected_frac_below_8db) by more than 0.05")
    }
}

// MARK: - Level meter tests

final class LevelMeterTests: XCTestCase {
    func testClipFraction() throws {
        let exp = try loadExpected()
        let (samples, sr) = try readWAV("clip_fixture.wav")

        // Use a single window that covers the entire file.
        let dur = Double(samples.count) / Double(sr)
        let meter = LevelMeter(sampleRate: Double(sr), windowDuration: dur)
        meter.clippingThreshold = Float(exp.clip.clipping_threshold)
        meter.push(samples)

        let expected = Float(exp.clip.expected_clip_fraction)
        let tol = expected * Float(exp.clip.tolerance_relative)

        XCTAssertEqual(meter.clipFraction, expected, accuracy: tol,
                       "Clip fraction \(meter.clipFraction) not within ±\(tol) of \(expected)")
    }

    func testRMSIsReasonable() {
        // Sine at 0.5 amplitude → RMS = 0.5/√2 ≈ 0.354 → ~-9 dBFS.
        let sr = 48_000
        let n  = sr  // 1 second
        var samples = [Float](repeating: 0, count: n)
        for i in 0..<n {
            let phase = 2.0 * Double.pi * 1000.0 * Double(i) / Double(sr)
            samples[i] = Float(0.5 * sin(phase))
        }

        let meter = LevelMeter(sampleRate: Double(sr), windowDuration: 1.0)
        meter.push(samples)

        let expectedRMSLinear = Float(0.5 / sqrt(2.0))
        let expectedDB = 20.0 * log10(expectedRMSLinear)  // ≈ -9.03 dBFS
        XCTAssertEqual(meter.rmsDB, expectedDB, accuracy: 0.5,
                       "RMS dB \(meter.rmsDB) not within 0.5 dB of \(expectedDB)")
        XCTAssertEqual(meter.clipFraction, 0.0, accuracy: 0.001,
                       "Unexpected clipping in clean sine")
    }

    func testPeakDetection() {
        // Single full-scale spike → peak = 1.0 → 0 dBFS.
        var samples = [Float](repeating: 0, count: 4800)
        samples[2400] = 1.0

        let meter = LevelMeter(sampleRate: 48_000, windowDuration: 0.1)
        meter.push(samples)

        XCTAssertEqual(meter.peakDB, 0.0, accuracy: 0.01)
    }
}

// MARK: - Setup grader tests

final class SetupGraderTests: XCTestCase {
    func testRobustPass() {
        let metrics = CaptureMetrics(
            snrDBMedian: 36.0, snrDBP10: 28.0, fracBelow8dB: 0.05,
            flutterWRMSPct: 0.40, noiseFloorDBFS: -50.0,
            isLossless: true, hasClipping: false)
        let result = SetupGrader.grade(metrics: metrics)
        XCTAssertEqual(result.robust.verdict, .pass)
    }

    func testClippingAlwaysFails() {
        let metrics = CaptureMetrics(
            snrDBMedian: 45.0, snrDBP10: 42.0, fracBelow8dB: 0.0,
            isLossless: true, hasClipping: true)
        let result = SetupGrader.grade(metrics: metrics)
        XCTAssertEqual(result.robust.verdict, .fail)
        XCTAssertEqual(result.turbo.verdict, .fail)
        XCTAssertEqual(result.moonshot.verdict, .fail)
    }

    func testNonLosslessBlocksTurbo() {
        let metrics = CaptureMetrics(
            snrDBMedian: 38.0, snrDBP10: 34.0, fracBelow8dB: 0.0,
            isLossless: false, hasClipping: false)
        let result = SetupGrader.grade(metrics: metrics)
        XCTAssertEqual(result.robust.verdict, .pass)
        XCTAssertEqual(result.turbo.verdict, .fail)
        XCTAssertTrue(result.turbo.advice.lowercased().contains("lossless"),
                      "Expected 'lossless' in advice: \(result.turbo.advice)")
    }

    func testMoonshotRequiresHighSNR() {
        // SNR median 37 is within moonshot marginal band (38 - 2 = 36) → marginal.
        // To get a hard fail, use SNR 35 (below 38 - 2 = 36).
        let metrics = CaptureMetrics(
            snrDBMedian: 35.0, snrDBP10: 31.5, fracBelow8dB: 0.0,
            flutterWRMSPct: 0.40,
            isLossless: true, hasClipping: false)
        let result = SetupGrader.grade(metrics: metrics)
        // SNR median 35 < moonshot threshold 38 - band 2 = 36 → fail.
        XCTAssertEqual(result.moonshot.verdict, .fail,
                       "SNR 35 is below moonshot marginal band floor (36), should fail")
    }

    func testMarginalBand() {
        // SNR median = 32 dB: below robust min (33) but within 3 dB marginal band → marginal.
        // Set p10 also within its marginal band (25-3=22, so 23 is marginal).
        // fracBelow8dB well within limit, no flutter, lossless, no clipping.
        let metrics = CaptureMetrics(
            snrDBMedian: 32.0, snrDBP10: 23.5, fracBelow8dB: 0.0,
            isLossless: true, hasClipping: false)
        let result = SetupGrader.grade(metrics: metrics)
        XCTAssertEqual(result.robust.verdict, .marginal,
                       "Expected marginal for SNR 32 (band 30–33), p10 23.5 (band 22–25)")
    }

    func testHighestPassingTier() {
        // Meets robust and turbo but not moonshot.
        let metrics = CaptureMetrics(
            snrDBMedian: 37.0, snrDBP10: 31.0, fracBelow8dB: 0.05,
            flutterWRMSPct: 0.43,
            isLossless: true, hasClipping: false)
        let result = SetupGrader.grade(metrics: metrics)
        XCTAssertNotNil(result.highestPassing)
    }
}

// MARK: - Waterfall processor tests

final class WaterfallProcessorTests: XCTestCase {
    func testBinCount() {
        let wp = WaterfallProcessor(fftSize: 1024, hopSize: 512,
                                    sampleRate: 48_000, freqLo: 0, freqHi: 12_000)
        XCTAssertGreaterThan(wp.binCount, 0)
        XCTAssertLessThanOrEqual(wp.binCount, 1024 / 2 + 1)
    }

    func testEmitsRows() {
        let wp = WaterfallProcessor(fftSize: 1024, hopSize: 512, sampleRate: 48_000)
        let silence = [Float](repeating: 0, count: 2048)
        wp.push(silence)
        let rows = wp.drainRows()
        XCTAssertGreaterThanOrEqual(rows.count, 1)
        if let first = rows.first {
            XCTAssertEqual(first.count, wp.binCount)
        }
    }

    func testRowValuesNormalized() {
        let wp = WaterfallProcessor(fftSize: 1024, hopSize: 512, sampleRate: 48_000)
        let n = 48_000
        var tone = [Float](repeating: 0, count: n)
        for i in 0..<n {
            let phase = 2.0 * Double.pi * 1_000.0 * Double(i) / 48_000.0
            tone[i] = Float(0.5 * sin(phase))
        }
        wp.push(tone)
        let rows = wp.drainRows()
        XCTAssertFalse(rows.isEmpty)
        for row in rows {
            for v in row {
                XCTAssertGreaterThanOrEqual(v, 0.0, "Row value below 0: \(v)")
                XCTAssertLessThanOrEqual(v,   1.0, "Row value above 1: \(v)")
            }
        }
    }
}
