//! End-to-end byte-exact parity test for the R-1 combo-MFSK floor rung.
//!
//! Loads the golden fixtures generated by
//! `experiments/tape_v2/rust_fixtures/gen_floor_fixtures.py` (run that first)
//! and asserts the Rust decoder recovers the floor payload BYTE-EXACT from the
//! globally-synced `audio_nominal`, across the clean / normal / worn channels —
//! the same proof `test_fullspectrum_floor.py` makes on the Python side.

use cassette_codec::decoder::{
    decode_combo_section, decode_floor_from_capture, FloorManifest, FloorSection,
};
use cassette_codec::framing::ComboMeta;
use serde::Deserialize;
use std::path::PathBuf;

#[derive(Deserialize)]
struct Sync {
    align: i64,
    tx_chirp0: i64,
    tx_chirp1: i64,
}
#[derive(Deserialize)]
struct Section {
    frame_starts: Vec<i64>,
    body_end: i64,
    guard_samples: i64,
}
#[derive(Deserialize)]
struct Meta {
    #[serde(rename = "M")]
    m: usize,
    #[serde(rename = "K")]
    k: usize,
    rs_n: usize,
    rs_k: usize,
    n_codewords: usize,
    frame_bits: usize,
    n_frames: usize,
    stream_bits: usize,
    payload_len: usize,
}
#[derive(Deserialize)]
struct Fixture {
    label: String,
    byte_exact_python: bool,
    sync: Sync,
    section: Section,
    meta: Meta,
    payload: Vec<u8>,
}

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../experiments/tape_v2/rust_fixtures/fixtures")
}

fn load_wav_f64(path: &PathBuf) -> Vec<f64> {
    let mut reader = hound::WavReader::open(path)
        .unwrap_or_else(|e| panic!("open {}: {e}\nRun gen_floor_fixtures.py first.", path.display()));
    let spec = reader.spec();
    assert_eq!(spec.channels, 1, "fixtures are mono");
    match spec.sample_format {
        hound::SampleFormat::Float => reader
            .samples::<f32>()
            .map(|s| s.unwrap() as f64)
            .collect(),
        hound::SampleFormat::Int => {
            let max = (1i64 << (spec.bits_per_sample - 1)) as f64;
            reader
                .samples::<i32>()
                .map(|s| s.unwrap() as f64 / max)
                .collect()
        }
    }
}

fn decode_channel(label: &str) -> (bool, usize) {
    let dir = fixtures_dir();
    let json = std::fs::read_to_string(dir.join(format!("{label}.json")))
        .unwrap_or_else(|e| panic!("read {label}.json: {e}\nRun gen_floor_fixtures.py first."));
    let fx: Fixture = serde_json::from_str(&json).expect("parse fixture json");
    assert!(fx.byte_exact_python, "fixture {label} was not byte-exact in Python — regenerate");

    let audio = load_wav_f64(&dir.join(format!("{label}_nominal.wav")));

    let section = FloorSection {
        m: fx.meta.m,
        k: fx.meta.k,
        f_low: cassette_codec::decoder::DEFAULT_F_LOW,
        f_high: cassette_codec::decoder::DEFAULT_F_HIGH,
        frame_starts: fx.section.frame_starts.clone(),
        body_end: fx.section.body_end,
        guard: fx.section.guard_samples,
    };
    let meta = ComboMeta {
        rs_n: fx.meta.rs_n,
        rs_k: fx.meta.rs_k,
        n_codewords: fx.meta.n_codewords,
        frame_bits: fx.meta.frame_bits,
        n_frames: fx.meta.n_frames,
        stream_bits: fx.meta.stream_bits,
        payload_len: fx.meta.payload_len,
    };

    let dec = decode_combo_section(&audio, &section, fx.sync.align, &meta);
    let byte_exact = dec.bytes == fx.payload;
    let byte_errors = dec
        .bytes
        .iter()
        .zip(fx.payload.iter())
        .filter(|(a, b)| a != b)
        .count()
        + (dec.bytes.len() as i64 - fx.payload.len() as i64).unsigned_abs() as usize;
    eprintln!(
        "[rust] {:6} byte_exact={} cwFail={}/{} byteErr={} ({} bytes)",
        fx.label, byte_exact, dec.codewords_failed, meta.n_codewords, byte_errors, fx.payload.len()
    );
    (byte_exact, byte_errors)
}

/// Full pipeline: decode straight from the RAW capture (pre global-sync), the
/// way a real mic/line-in recording arrives at the companion app.
fn decode_capture(label: &str) -> bool {
    let dir = fixtures_dir();
    let json = std::fs::read_to_string(dir.join(format!("{label}.json"))).unwrap();
    let fx: Fixture = serde_json::from_str(&json).unwrap();
    let raw = load_wav_f64(&dir.join(format!("{label}_raw.wav")));

    let manifest = FloorManifest {
        tx_chirp0: fx.sync.tx_chirp0,
        tx_chirp1: fx.sync.tx_chirp1,
        section: FloorSection {
            m: fx.meta.m,
            k: fx.meta.k,
            f_low: cassette_codec::decoder::DEFAULT_F_LOW,
            f_high: cassette_codec::decoder::DEFAULT_F_HIGH,
            frame_starts: fx.section.frame_starts.clone(),
            body_end: fx.section.body_end,
            guard: fx.section.guard_samples,
        },
        meta: ComboMeta {
            rs_n: fx.meta.rs_n,
            rs_k: fx.meta.rs_k,
            n_codewords: fx.meta.n_codewords,
            frame_bits: fx.meta.frame_bits,
            n_frames: fx.meta.n_frames,
            stream_bits: fx.meta.stream_bits,
            payload_len: fx.meta.payload_len,
        },
    };
    let res = decode_floor_from_capture(&raw, &manifest);
    let ok = res.payload.bytes == fx.payload;
    eprintln!(
        "[rust/capture] {:6} byte_exact={} speed={:.4} align={:+} cwFail={}/{}",
        label, ok, res.speed, res.align, res.payload.codewords_failed, manifest.meta.n_codewords
    );
    ok
}

#[test]
fn floor_clean_byte_exact() {
    let (ok, _) = decode_channel("clean");
    assert!(ok, "clean master must decode byte-exact (M1)");
}

#[test]
fn capture_clean_byte_exact() {
    assert!(decode_capture("clean"), "raw clean capture must decode byte-exact end-to-end");
}

#[test]
fn capture_normal_byte_exact() {
    assert!(decode_capture("normal"), "raw normal capture must decode byte-exact end-to-end");
}

#[test]
fn capture_worn_byte_exact() {
    assert!(decode_capture("worn"), "raw worn+-0.12 capture must decode byte-exact end-to-end");
}

#[test]
fn floor_normal_byte_exact() {
    let (ok, _) = decode_channel("normal");
    assert!(ok, "normal cassette channel must decode byte-exact (M2)");
}

#[test]
fn floor_worn_byte_exact() {
    let (ok, _) = decode_channel("worn");
    assert!(ok, "worn+-0.12 cassette channel must decode byte-exact (M2)");
}
