//! Byte-exact parity test for the NARROWBAND (470-2200 Hz) combinatorial-MFSK
//! M12/K2 RS(255,95) MNIST floor master.
//!
//! Loads the golden fixture generated by
//! `experiments/tape_v2/rust_fixtures/gen_narrowband_fixture.py` (run that first)
//! and asserts the BAND-parameterized Rust combo path
//! (`ComboScheme::new_band` via `FloorSection.f_low/f_high`) recovers
//! `payloads/llm_tape_fit/mnist/mnist-12.onnx` BYTE-EXACT from the globally-synced
//! `narrowband_nominal.wav` — the same proof make_narrowband_master.verify() makes
//! on the Python side.

use cassette_codec::decoder::{decode_combo_section, FloorSection};
use cassette_codec::framing::ComboMeta;
use serde::Deserialize;
use std::path::PathBuf;

#[derive(Deserialize)]
struct Sync {
    align: i64,
}
#[derive(Deserialize)]
struct Section {
    #[serde(rename = "M")]
    m: usize,
    #[serde(rename = "K")]
    k: usize,
    f_low: f64,
    f_high: f64,
    frame_starts: Vec<i64>,
    body_end: i64,
    guard_samples: i64,
}
#[derive(Deserialize)]
struct Meta {
    #[serde(rename = "M")]
    _m: usize,
    #[serde(rename = "K")]
    _k: usize,
    rs_n: usize,
    rs_k: usize,
    n_codewords: usize,
    frame_bits: usize,
    n_frames: usize,
    stream_bits: usize,
    payload_len: usize,
}
#[derive(Deserialize)]
struct Fixture {
    byte_exact_python: bool,
    sync: Sync,
    section: Section,
    meta: Meta,
    payload: Vec<u8>,
}

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../experiments/tape_v2/rust_fixtures/fixtures")
}

fn load_wav_f64(path: &PathBuf) -> Vec<f64> {
    let mut reader = hound::WavReader::open(path).unwrap_or_else(|e| {
        panic!("open {}: {e}\nRun gen_narrowband_fixture.py first.", path.display())
    });
    let spec = reader.spec();
    assert_eq!(spec.channels, 1, "fixture is mono");
    match spec.sample_format {
        hound::SampleFormat::Float => {
            reader.samples::<f32>().map(|s| s.unwrap() as f64).collect()
        }
        hound::SampleFormat::Int => {
            let max = (1i64 << (spec.bits_per_sample - 1)) as f64;
            reader
                .samples::<i32>()
                .map(|s| s.unwrap() as f64 / max)
                .collect()
        }
    }
}

#[test]
fn narrowband_mnist_byte_exact() {
    let dir = fixtures_dir();
    let json = std::fs::read_to_string(dir.join("narrowband.json"))
        .unwrap_or_else(|e| panic!("read narrowband.json: {e}\nRun gen_narrowband_fixture.py first."));
    let fx: Fixture = serde_json::from_str(&json).expect("parse fixture json");
    assert!(
        fx.byte_exact_python,
        "fixture was not byte-exact in Python — regenerate"
    );

    let audio = load_wav_f64(&dir.join("narrowband_nominal.wav"));

    let section = FloorSection {
        m: fx.section.m,
        k: fx.section.k,
        f_low: fx.section.f_low,
        f_high: fx.section.f_high,
        frame_starts: fx.section.frame_starts.clone(),
        body_end: fx.section.body_end,
        guard: fx.section.guard_samples,
    };
    let meta = ComboMeta {
        rs_n: fx.meta.rs_n,
        rs_k: fx.meta.rs_k,
        n_codewords: fx.meta.n_codewords,
        frame_bits: fx.meta.frame_bits,
        n_frames: fx.meta.n_frames,
        stream_bits: fx.meta.stream_bits,
        payload_len: fx.meta.payload_len,
    };

    let dec = decode_combo_section(&audio, &section, fx.sync.align, &meta);
    let byte_exact = dec.bytes == fx.payload;
    let byte_errors = dec
        .bytes
        .iter()
        .zip(fx.payload.iter())
        .filter(|(a, b)| a != b)
        .count()
        + (dec.bytes.len() as i64 - fx.payload.len() as i64).unsigned_abs() as usize;
    eprintln!(
        "[rust] narrowband M{}K{} band {:.0}-{:.0}Hz byte_exact={} cwFail={}/{} byteErr={} ({} bytes)",
        section.m, section.k, section.f_low, section.f_high,
        byte_exact, dec.codewords_failed, meta.n_codewords, byte_errors, fx.payload.len()
    );
    assert!(
        byte_exact,
        "narrowband MNIST master must decode byte-exact via the band-parameterized combo path"
    );
}
