//! Byte-exact parity test for the R0 RESCUE ENSEMBLE on a HARD ACOUSTIC capture.
//!
//! Loads the real Voice-Memos acoustic fixture
//! (`experiments/tape_v2/rust_fixtures/fixtures/vm38_r0.json` + `vm38_nominal.wav`,
//! generated by `gen_vm38_r0_fixture.py`), globally-synced to nominal. The
//! single-pass front-end decodes only 29/31 codewords; the rescue ensemble
//! (CRC32-guarded EMA front-end bank union + late-window dc0 stitched branches)
//! must recover all 31 -> BYTE-EXACT payload, matching Python's rescue=True
//! (winning branch `lw_ema0.6_S16`).

use cassette_codec::dqpsk::{decode_r0_ensemble, R0Section};
use cassette_codec::framing::ComboMeta;
use serde::Deserialize;
use std::path::PathBuf;

#[derive(Deserialize)]
struct Section {
    frame_starts: Vec<i64>,
    body_end: i64,
    p: usize,
    n: usize,
    spacing: usize,
    skip: Option<usize>,
    pilot_hz: f64,
}
#[derive(Deserialize)]
struct Meta {
    rs_n: usize,
    rs_k: usize,
    n_codewords: usize,
    frame_bits: usize,
    n_frames: usize,
    stream_bits: usize,
    payload_len: usize,
}
#[derive(Deserialize)]
struct Vm38Fixture {
    align: i64,
    section: Section,
    meta: Meta,
    crc32_codewords: Vec<u32>,
    payload: Vec<u8>,
}

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../experiments/tape_v2/rust_fixtures/fixtures")
}

fn load_wav_f64(path: &PathBuf) -> Vec<f64> {
    let mut reader = hound::WavReader::open(path).unwrap_or_else(|e| {
        panic!(
            "open {}: {e}\nRun gen_vm38_r0_fixture.py first.",
            path.display()
        )
    });
    let spec = reader.spec();
    assert_eq!(spec.channels, 1, "fixtures are mono");
    match spec.sample_format {
        hound::SampleFormat::Float => reader.samples::<f32>().map(|s| s.unwrap() as f64).collect(),
        hound::SampleFormat::Int => {
            let max = (1i64 << (spec.bits_per_sample - 1)) as f64;
            reader.samples::<i32>().map(|s| s.unwrap() as f64 / max).collect()
        }
    }
}

#[test]
fn vm38_rescue_ensemble_byte_exact() {
    let dir = fixtures_dir();
    let json = std::fs::read_to_string(dir.join("vm38_r0.json")).unwrap_or_else(|e| {
        panic!("read vm38_r0.json: {e}\nRun gen_vm38_r0_fixture.py first.")
    });
    let fx: Vm38Fixture = serde_json::from_str(&json).expect("parse vm38_r0.json");

    let audio = load_wav_f64(&dir.join("vm38_nominal.wav"));

    let section = R0Section {
        p: fx.section.p,
        n: fx.section.n,
        spacing: fx.section.spacing,
        skip: fx.section.skip,
        pilot_hz: fx.section.pilot_hz,
        frame_starts: fx.section.frame_starts.clone(),
        body_end: fx.section.body_end,
    };
    let meta = ComboMeta {
        rs_n: fx.meta.rs_n,
        rs_k: fx.meta.rs_k,
        n_codewords: fx.meta.n_codewords,
        frame_bits: fx.meta.frame_bits,
        n_frames: fx.meta.n_frames,
        stream_bits: fx.meta.stream_bits,
        payload_len: fx.meta.payload_len,
    };

    let dec = decode_r0_ensemble(&audio, &section, fx.align, &meta, &fx.crc32_codewords);
    let byte_errors = dec
        .bytes
        .iter()
        .zip(fx.payload.iter())
        .filter(|(a, b)| a != b)
        .count()
        + (dec.bytes.len() as i64 - fx.payload.len() as i64).unsigned_abs() as usize;
    eprintln!(
        "[rust/r0-ensemble] vm38 align={:+} cwFail={}/{} byteErr={} ({} bytes)",
        fx.align, dec.codewords_failed, meta.n_codewords, byte_errors, fx.payload.len()
    );
    assert_eq!(
        dec.codewords_failed, 0,
        "rescue ensemble must recover all codewords (got {}/{} failed)",
        dec.codewords_failed, meta.n_codewords
    );
    assert_eq!(dec.bytes, fx.payload, "vm38 rescue ensemble must be byte-exact");
}
