//! End-to-end byte-exact parity test for the R0 robust coherent-DQPSK rung.
//!
//! Loads the golden fixtures generated by
//! `experiments/tape_v2/rust_fixtures/gen_r0_fixtures.py` (run gen_floor_fixtures.py
//! first, then gen_r0_fixtures.py) and asserts the Rust DQPSK decoder recovers the
//! R0 payload BYTE-EXACT from the globally-synced `audio_nominal`, across the
//! clean / normal / worn channels — the same proof the Python reference makes.

use cassette_codec::dqpsk::{decode_r0_section, R0Section};
use cassette_codec::framing::ComboMeta;
use serde::Deserialize;
use std::path::PathBuf;

#[derive(Deserialize)]
struct DqpskParams {
    #[serde(rename = "P")]
    p: usize,
    #[serde(rename = "N")]
    n: usize,
    spacing: usize,
    skip: Option<usize>,
    pilot_hz: f64,
}
#[derive(Deserialize)]
struct R0Meta {
    rs_n: usize,
    rs_k: usize,
    n_codewords: usize,
    frame_bits: usize,
    n_frames: usize,
    stream_bits: usize,
    payload_len: usize,
}
#[derive(Deserialize)]
struct R0Fixture {
    frame_starts: Vec<i64>,
    body_end: i64,
    dqpsk_params: DqpskParams,
    meta: R0Meta,
    payload: Vec<u8>,
}

#[derive(Deserialize)]
struct Sync {
    align: i64,
}
#[derive(Deserialize)]
struct ChanFixture {
    sync: Sync,
}

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../experiments/tape_v2/rust_fixtures/fixtures")
}

fn load_wav_f64(path: &PathBuf) -> Vec<f64> {
    let mut reader = hound::WavReader::open(path).unwrap_or_else(|e| {
        panic!(
            "open {}: {e}\nRun gen_floor_fixtures.py then gen_r0_fixtures.py first.",
            path.display()
        )
    });
    let spec = reader.spec();
    assert_eq!(spec.channels, 1, "fixtures are mono");
    match spec.sample_format {
        hound::SampleFormat::Float => reader.samples::<f32>().map(|s| s.unwrap() as f64).collect(),
        hound::SampleFormat::Int => {
            let max = (1i64 << (spec.bits_per_sample - 1)) as f64;
            reader.samples::<i32>().map(|s| s.unwrap() as f64 / max).collect()
        }
    }
}

fn load_r0() -> R0Fixture {
    let dir = fixtures_dir();
    let json = std::fs::read_to_string(dir.join("r0_section.json")).unwrap_or_else(|e| {
        panic!("read r0_section.json: {e}\nRun gen_r0_fixtures.py first.")
    });
    serde_json::from_str(&json).expect("parse r0_section.json")
}

fn decode_channel(label: &str) -> (bool, usize, usize) {
    let dir = fixtures_dir();
    let fx = load_r0();
    let chan_json = std::fs::read_to_string(dir.join(format!("{label}.json")))
        .unwrap_or_else(|e| panic!("read {label}.json: {e}"));
    let chan: ChanFixture = serde_json::from_str(&chan_json).expect("parse channel json");
    let align = chan.sync.align;

    let audio = load_wav_f64(&dir.join(format!("{label}_nominal.wav")));

    let section = R0Section {
        p: fx.dqpsk_params.p,
        n: fx.dqpsk_params.n,
        spacing: fx.dqpsk_params.spacing,
        skip: fx.dqpsk_params.skip,
        pilot_hz: fx.dqpsk_params.pilot_hz,
        frame_starts: fx.frame_starts.clone(),
        body_end: fx.body_end,
    };
    let meta = ComboMeta {
        rs_n: fx.meta.rs_n,
        rs_k: fx.meta.rs_k,
        n_codewords: fx.meta.n_codewords,
        frame_bits: fx.meta.frame_bits,
        n_frames: fx.meta.n_frames,
        stream_bits: fx.meta.stream_bits,
        payload_len: fx.meta.payload_len,
    };

    let dec = decode_r0_section(&audio, &section, align, &meta);
    let byte_exact = dec.bytes == fx.payload;
    let byte_errors = dec
        .bytes
        .iter()
        .zip(fx.payload.iter())
        .filter(|(a, b)| a != b)
        .count()
        + (dec.bytes.len() as i64 - fx.payload.len() as i64).unsigned_abs() as usize;
    eprintln!(
        "[rust/r0] {:6} align={:+} byte_exact={} cwFail={}/{} byteErr={} ({} bytes)",
        label, align, byte_exact, dec.codewords_failed, meta.n_codewords, byte_errors, fx.payload.len()
    );
    (byte_exact, byte_errors, dec.codewords_failed)
}

#[test]
fn r0_clean_byte_exact() {
    let (ok, _, cwf) = decode_channel("clean");
    assert!(ok, "clean R0 must decode byte-exact (cw_failed={cwf})");
}

#[test]
fn r0_normal_byte_exact() {
    let (ok, _, cwf) = decode_channel("normal");
    assert!(ok, "normal R0 must decode byte-exact (cw_failed={cwf})");
}

#[test]
fn r0_worn_byte_exact() {
    let (ok, _, cwf) = decode_channel("worn");
    assert!(ok, "worn+-0.12 R0 must decode byte-exact (cw_failed={cwf})");
}
